src/pnl.py: error: Source file found twice under different module names:
"config.risk.risk_config" and "src.config.risk.risk_config"
src/pnl.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
src/pnl.py: note: Common resolutions include: a) adding `__init__.py` somewhere, b) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)
